version: '3'
services:
    mosquitto:
        ports:
            - 1883:1883
            - 9001:9001  
        image: eclipse-mosquitto
        volumes: 
            - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./mosquitto/data:/mosquitto/data
        network_mode: host

