/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sensor;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        Sensor snsr = new Sensor("temperature", "127.0.0.1" ,"5556", "127.0.0.1", "5555");

        snsr.run();
    }
}
