/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weatherservice;

import java.net.InetAddress;
import java.net.UnknownHostException;

public class Weatherservice {
private InetAddress ipAddress;
private int port;
private String name;


    public Weatherservice(String n, String receiveIP, String receiveP, String serverIP, String serverP) {
        name = n;


        try {
            ipAddress = InetAddress.getByName(receiveIP);
            serverIpAddress = InetAddress.getByName(serverIP);
        } catch (UnknownHostException e) {
            System.out.println("Please enter a valid IP-Address");
        }
        port = Integer.parseInt(receiveP);
        serverPort = Integer.parseInt(serverP);
    }


    public static void main(String[] args)  {
        System.out.println("weatherservice");
    }
}
