/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weatherservice;


public class Weatherservice {
private int port;
private String name;

    public Weatherservice(String name, String port) {
        this.name = name;
        this.port = Integer.parseInt(port);
    }

    public static void main(String[] args)  {
        Weatherservice weatherservice = new Weatherservice(args[0],args[1]);
        System.out.println(weatherservice.name);

        RpcServer rpcServer = new RpcServer(weatherservice.port);
        Thread rpcServerThread = new Thread(rpcServer);
        rpcServerThread.start();
    }
}
